### ISSUE TITLE
Cannot find module 'vueify'

### ISSUE THREAD

**Issue by micheleivani** [JeffreyWay/laravel-elixir-vueify#1]
After following all instructions I got the following error after gulp run. 
`... Cannot find module 'vueify' ...`

I already discussed this issue on laracasts forum. Check it out for more details.
https://laracasts.com/discuss/channels/elixir/cannot-find-module-vueify

**Comment by JeffreyWay** [comment]
I can't reproduce this, after doing a fresh install of everything. All dependencies are there. I'm using:
- Node v5.1.0
- NPM v3.3.12

Sounds like you're using old versions of these??

**Comment by micheleivani** [comment]
Jeffrey, thanks so much for your reply. I had an old version of Node. So after upgrading it and re-run `npm install` again it seams working. 

As always great tools! Thanks
