### ISSUE TITLE
Huge files!

### ISSUE THREAD

**Issue by patrick-hertling** [JeffreyWay/laravel-elixir-vueify#10]
I just tried it out.
Made a hello world component and compiled it down with gulp and browserify.
Then I saw that the resulting *.js file is over 10.000 lines long. Even compressed its over 250kb.
That seems kind of a lot. Am I doing something wrong here?

**Comment by JeffreyWay** [comment]
Can you try `export NODE_ENV=production && gulp --production`, and then check the file size?

**Comment by patrick-hertling** [comment]
`C:\workspace\php\portal>echo %NODE_ENV%
production`

Yes. I just did, and its still the same size. 223kb. Sorry, earlier I said over 250, but 223 is still too much, right?

**Comment by stevenobird** [comment]
Well, it depends on how much you are pulling in.
When you're pulling in vuejs (and some more dependencies), that amount isn't too much.

I have a js file for vuejs, about 8 vue components and got a resulting file with 316kb (without production flag).
