### ISSUE TITLE
Vueify 8.4.1 wants babel-runtime v6

### ISSUE THREAD

**Issue by ghost** [JeffreyWay/laravel-elixir-vueify#14]
Hi

I'm receiving the following error when installing this package...

`
npm ERR! peerinvalid The package babel-runtime@5.8.38 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vueify@8.4.1 wants babel-runtime@^6.0.0
`

Having a look at the package.json dependencies it says it wants 

`
"babel-runtime": "^5.8.34",
"vueify": "^8.3.0"
`

Is this just an issue with me?!

**Comment by JeffreyWay** [comment]
We already do require v6 of babel-runtime.

https://github.com/vuejs/vueify/blob/master/package.json#L43

**Comment by ghost** [comment]
I deleted the node_modules directory and tried installing again but have this error...

`
npm WARN peerDependencies The peer dependency babel-runtime@^6.0.0 included from vueify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "laravel-elixir-vueify"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package babel-runtime@5.8.38 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer vueify@8.4.1 wants babel-runtime@^6.0.0
`

Any ideas how I can install it?

**Comment by mtx-z** [comment]
Same error here. Tried a lot of unistall/reinstall.

**Comment by greenleafmedia** [comment]
I'm getting this as well.

@JeffreyWay - Do you think it has something to do with the dependencies at https://github.com/JeffreyWay/laravel-elixir-vueify/blob/master/package.json?

That's the exact version of babel-runtime that's throwing the error.

**Comment by wtw24** [comment]
![2016-05-13_20-19-48](https://cloud.githubusercontent.com/assets/18031815/15257742/11c396be-1948-11e6-98aa-e6dc68ba58c0.jpeg)
Same error
[npm-debug.txt](https://github.com/JeffreyWay/laravel-elixir-vueify/files/263862/npm-debug.txt)

**Comment by ghost** [comment]
I fixed the problem by deleting everything again, updated node and npm then ran npm install. It all worked then.

**Comment by greenleafmedia** [comment]
Hmmm... I deleted everything and re-installed and I'm still getting the error.

My versions are:
$ node -v
v4.4.4

$ npm -v
2.15.1

@totalpeople - What versions are you running that are working successfully?

EDIT - I used nvm to update node to 6.1.0 and everything is working again for me.

**Comment by bertog** [comment]
I cannot sort this out. Upgrade node to v.6.1.0 doesn't work for me. Could someone please tell the exact node version and npm version to install the package? Thanks.

EDIT: by the way after node upgrade (6.1.0) I receive a WARN during the installation claiming for babel v5.8.34, but using the component with elixir and gulp seems to compile component without problems.

**Comment by EmilMoe** [comment]
Same error here, it's not fixed.

Node 4.4.4 is the long term supported Node version

**Comment by mtx-z** [comment]
Hey, after lot of tests a finally worked it out. But i dont know exactly how.

Windows
npm -v 3.5.1
node -v 4.4.4

In my package.json
    "laravel-elixir-vueify": "^1.0.3",
    "vue": "^1.0.21",
    "vue-resource": "^0.7.0"

I made a lot of tries installing and uninstlaling babel-soemthing. 

From npm list
│ ├── babel-plugin-transform-runtime@6.8.0
│ ├─┬ babel-runtime@5.8.38

and some others version.

Also done npm install --save-dev babel-preset-es2015 from https://babeljs.io/

**Comment by rogervila** [comment]
Hi @mtx-z,
When I run `npm list` all babel-\* items have a @6.n.n version, and I get this message: `EPEERINVALID vueify@8.4.1 requires a peer of babel-runtime@^6.0.0 but none was installed.`
The package works but the output file has import, export and require methods, so I suppose that babel is not translating the es6 code into old js.
I have node 5.0.0 and npm 3.4.1

**Comment by mtx-z** [comment]
I had basicly the same problem. 
So i tried install manualy all babel dependencides one by one (from my package.json).
Finally, it didn't worked. So i removed the Babel stuff from my package, and removed vuefy to make some npm shell stuff. 
Then i putted back vuefiy and it passed. 
Told you, this is kind of a "miracle" ...

**Comment by mtx-z** [comment]
Try to : 
delete all your node_modules folder (for error of name/path on delete on Windows, search for robocopy). 
try npm install when the folder is fully deleted.

**Comment by ClaraLeigh** [comment]
@greenleafmedia 

> @JeffreyWay - Do you think it has something to do with the dependencies at https://github.com/JeffreyWay/laravel-elixir-vueify/blob/master/package.json?

Can confirm that updating package.json to use babel-runtime: ^6.0.0 fixes the issue.
https://github.com/JeramyNS/laravel-elixir-vueify/commit/1087abb606433a060c3e71d15c0131996d646a86
