### ISSUE TITLE
how hot reload works with laravel-elixir browserify?

### ISSUE THREAD

**Issue by cnweibo** [JeffreyWay/laravel-elixir-vueify#17]
Hi, jeffery,
Previously, i use browsersync to inject css without reloading page when developing css using less.
Currenlty, i switched to use laravel-exlixir-vueify to develop components.
In that .vue file, the less styling will be compiled when changed.
Unfortunately, the page itself reloads everytime, it is annoying.
Can we support hot reloading compiled css without page reloading?
In webpack, there is something for that purpose.
In laravel browserify community, i do not know how make that work.
Do you know about that?
Thanks~!

**Comment by JeffreyWay** [comment]
I'm not positive how to do it with Browserify and a PHP server at the moment.

Pull requests appreciated, if anyone wants to tackle it!
