### ISSUE TITLE
Doesn't load components

### ISSUE THREAD

**Issue by Hebilicious** [JeffreyWay/laravel-elixir-vueify#2]
I went with a fresh laravel install and a simple gulpfile to try-out the new laravel-elixir.

gulpfile.js

``` javascript
var elixir = require('laravel-elixir');
require('laravel-elixir-vueify');

elixir(function(mix) {
    mix.browserify("app.js");
});
```

app.js

``` javascript
var Vue = require('vue');
Vue.config.debug = true;

import App from "./thisapp.vue";

var app = new Vue({
    el: '#app',
    components: {
        application: App,
    },
    ready()
    {
        console.log('Root is ready');
    }
});
```

app.vue

``` javascript
<style>
body{
    background-color : green;
    color: white;
}
</style>

<template>
    <h1>Hello World</h1>
    <pre>{{ $data | json }}</pre>
</template>

<script>
export default{
    data()
    {
        return {
            example: "test"
        }
    },
    ready()
    {
        console.log('Ready');
    }
};
</script>
```

Compilation works properly, but there's nothing in the webpage. However removing the require('laravel-elixir-vueify') and manually requiring vueify-insert-css/vue-hot-reload-api 
make everything works properly.

**Comment by JeffreyWay** [comment]
I can't reproduce this.

Here's a starter example repo you can review:

https://github.com/laracasts/Laravel-Elixir-Vueify-Setup

**Comment by ganicus** [comment]
@Hebilicious did you ever resolve? I'm having the same issue.

Did you have to add/remove anything from your package.json?

**Comment by Hebilicious** [comment]
@ganicus I've stopped using this package since I couldn't figure out why. Try updating your deps and switch to npm3? Otherwise you can do it manually : https://laracasts.com/discuss/channels/vue/how-to-elixir-vue-browsersync-vueify-hotreload
