### ISSUE TITLE
Cannot read property 'transformers' of undefined

### ISSUE THREAD

**Issue by nmfzone** [JeffreyWay/laravel-elixir-vueify#24]
I don't know it's an issue with Node or with Elixir, but i get those result when i ran gulp.

This is details of my env : 

```
Node: v6.1.0
Elixir: ^6.0.0-9
Laravel-elixir-vueify: ^1.0.3
```

**Comment by JeffreyWay** [comment]
I need the full output message please.

**Comment by nmfzone** [comment]
This is the complete output, @JeffreyWay.

```
~Project/node_modules/laravel-elixir-vueify/index.js:3
Elixir.config.js.browserify.transformers.push({
                           ^

TypeError: Cannot read property 'transformers' of undefined
    at Object.<anonymous> (~Project/node_modules/laravel-elixir-vueify/index.js:3:28)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (~Project/gulpfile.js:3:1)
    at Module._compile (module.js:541:32)
```

"**~Project**" for readability

**Comment by nmfzone** [comment]
How do i fix this @JeffreyWay ?

**Comment by tormjens** [comment]
This is what I did to make it work:

`npm install --save-dev laravel-elixir-browserify-official laravel-elixir-vueify`

Add these two to your gulpfile

``` js
require('laravel-elixir-browserify-official');
require('laravel-elixir-vueify');
```

Doesn't look like the browserify config is availiable yet at the start of the gulpfile. Probably some kind of Laravel-like magic which makes everything work later.

**Comment by nmfzone** [comment]
@tormjens That's cool, I don't know that (the last paragraph). I just use what someone does in their PR #23. But now, I think we could forget this issue, because of [this commit](https://github.com/JeffreyWay/laravel-elixir-vueify/commit/c28459d54607e9a2d307ef4ff04499ab93615db2).

**Comment by GMory** [comment]
I'm still getting the same error even with that [latest commit](https://github.com/JeffreyWay/laravel-elixir-vueify/commit/c28459d54607e9a2d307ef4ff04499ab93615db2).

**Comment by nmfzone** [comment]
We still need to pull **laravel-elixir-browserify-official**, but we don't need to "require" it in our **gulpfile.js**.
