### ISSUE TITLE
does this work with laravel 5.3.18 and vue2?

### ISSUE THREAD

**Issue by steve-rhodes** [JeffreyWay/laravel-elixir-vueify#33]
I get an error when running `gulp` after following your instructions to install.

Also, what about the line `require('laravel-elixir-vue-2');` in gulpfile.js? Are we supposed to remove it?

error:

```
    Elixir.config.js.browserify.transformers.push({
                               ^

TypeError: Cannot read property 'transformers' of undefined
```

**Comment by echr** [comment]
check issue #24 ,, you need to npm install laravel-elixir-browserify-official and add `require('laravel-elixir-browserify-official');` in the gulp file.

**Comment by steve-rhodes** [comment]
thanks
