### ISSUE TITLE
Vue files not watched

### ISSUE THREAD

**Issue by skyronic** [JeffreyWay/laravel-elixir-vueify#5]
This isn't watching *.vue files and updating the build when I run `gulp watch`. Can you add support for this as well? Thanks!

**Comment by stevenobird** [comment]
I noticed that sometimes they are watched, sometimes not.

**Comment by skyronic** [comment]
I noticed this recently too. But the point to note is that vueify works well with watchify, so it's probably not an issue with laravel-elixir-vueify itself.

@twaileit if you can reliably reproduce a case where updates aren't getting triggered, I'll be happy to isolate the cause and file an issue with the right project - whether it's with elixir, browserify or vueify.

**Comment by stevenobird** [comment]
I just can say that small changes are not watched (e.g. some new-lines or spaces), but changes that go beyond that are noticed.

**Comment by jonagoldman** [comment]
I have this problem on Linux.
In my case it can be fixed adding `elixir.config.js.browserify.watchify.options.poll = true;` to `gulpfile.js`.

**Comment by skyronic** [comment]
@jonagoldman: Thanks a ton! This works like a charm on my Linux system!! Looks like this isn't an issue with laravel-elixir-vueify but rather the underlying filesystem watching library, so am closing this issue.

**Comment by hedii** [comment]
@jonagoldman thank you! save my day (osx)

**Comment by alshuwaikhat** [comment]
@jonagoldman Worked like a charm (osx); Thank you!

**Comment by alshuwaikhat** [comment]
@jonagoldman Worked like a charm (osx); Thank you!

**Comment by ikristher** [comment]
Thank you very much. It fixed the problem
