### ISSUE TITLE
Bump dependencies?

### ISSUE THREAD

**Issue by jonagoldman** [JeffreyWay/laravel-elixir-vueify#6]
:)

**Comment by seblavoie** [comment]
I suppose the error I am getting is related to this issue. Here's the error: 

```
UNMET PEER DEPENDENCY babel-preset-es2015@^6.1.2
```

I am not sure how to bump this dependency myself as I'm not very familiar with the mechanics of npm, but @jonagoldman you seem to know what's going on here. Care to explain a bit why this would happen please?

**Comment by laracasts** [comment]
Which ones? PR?
