### ISSUE TITLE
Vue Devtools still accessable with minimized JS

### ISSUE THREAD

**Issue by PhillippOhlandt** [JeffreyWay/laravel-elixir-vueify#7]
Normally you shouldn't be able to access the Vue Devtools on the minimized JS (`gulp --production`)

**Comment by PhillippOhlandt** [comment]
ping @JeffreyWay

**Comment by laracasts** [comment]
Can you try:

```
export NODE_ENV=production && gulp --production
```

Does that work?

**Comment by PhillippOhlandt** [comment]
Yep that works, thank you :)
