### ISSUE TITLE
Can't get .vue components to work | ParseError: Unexpected token: <template>

### ISSUE THREAD

**Issue by PhillippOhlandt** [JeffreyWay/laravel-elixir-vueify#8]
Short version: I set up everything like in the readme and the example application and it doesn't work.
Already posted in the laracasts forum and some people have the same problem but there is still no solution.

Read here:
https://laracasts.com/discuss/channels/vue/parseerror-unexpected-token-template?page=1

**Comment by PhillippOhlandt** [comment]
I don't expect any support here anymore.

**Comment by laracasts** [comment]
@PhillippOhlandt You need to watch that edge, man. It's the weekend.

**Comment by PhillippOhlandt** [comment]
There was no weekend 5 days ago as I asked in the forum. And after today I don't expect any support on some repos anymore.
